version: '3.9'
services:
  api:
    build: .
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
